name = "fortran_test_helper"
version = "1.0.1"
author = "Jason Christopherson"
maintainer = "Jason Christopherson"
copyright = "Copyright 2023-2025, Jason Christopherson"
license = "GPL-3.0"
description = "A Fortran library to provide assistance to testing."
homepage = "https://github.com/jchristopherson/fortran_test_helper"

[build]
auto-executables = false
auto-examples = false
auto-tests = false

[library]
source-dir = "src"

[install]
library = true
